export const SLIDES = [
  {
    id: 1,
    title: 'Cover',
    layerTag: null,
    color: '#0D1B3D',
    heading: 'LAB 3: BUILD THE PLATFORM',
    sub: 'PGB AI Platform Roadmap · 4 Lessons + Capstone · Read · Build · Present',
    body: [
      { type: 'layers', items: [
        { label: 'L1 · NetSuite ERP', tag: 'LIVE', tagColor: '#16A34A', color: '#C0392B' },
        { label: 'L2 · PGB SCE', tag: 'BUILD', tagColor: '#F59E0B', color: '#1E40AF' },
        { label: 'L3 · PGB AI Intel', tag: 'BUILD', tagColor: '#F59E0B', color: '#0D9488' },
      ]},
    ],
    question: null,
    dialogue: [
      { type: 'timing', time: '0:00 — 0:05', phase: 'PHASE: WELCOME' },
      { type: 'note', text: 'Open the app on the shared screen before participants arrive. Test the session sync.' },
      { type: 'say', text: 'Good morning, everyone. Welcome to Lab 3 of the PGB AI Lab Series — Build the Platform.' },
      { type: 'say', text: 'In the first two labs, we studied platforms like Blue Yonder and C3 AI — tools enterprises buy. Today, Lab 3 takes a very different direction.' },
      { type: 'say', text: 'Today we are not studying what someone else built. Today we are studying what PGB is building. Our own platform. Our own IP. Our own intelligence.' },
      { type: 'note', text: "Pause here. Let that land. The shift from 'we study tools' to 'we build tools' is the emotional pivot point of this lab." },
      { type: 'say', text: 'Let me ask you a question. If you had to choose — would you rather rent a house or own a house?' },
      { type: 'say', text: 'Exactly. PGB has been renting intelligence from platforms. Today, we start building a home we own.' },
    ],
  },
  {
    id: 2,
    title: 'Programme Overview',
    layerTag: null,
    color: '#0D1B3D',
    heading: 'LAB 3 PROGRAMME OVERVIEW',
    sub: '4 Lessons + Capstone · ~90 minutes',
    body: [
      { type: 'modgrid', items: [
        { num: '3.1', title: 'Why PGB Builds Its Own AI', time: '15 min', color: '#1E40AF' },
        { num: '3.2', title: 'PGB Supply Chain Engine', time: '20 min', color: '#1E40AF' },
        { num: '3.3', title: 'PGB AI Intel', time: '20 min', color: '#0D9488' },
        { num: '3.4', title: 'The 3-Layer Architecture', time: '15 min', color: '#7C3AED' },
        { num: '★', title: 'Capstone: Design Your Module', time: '20 min', color: '#F59E0B' },
      ]},
    ],
    question: { id: 'q2', prompt: 'What are you most curious to learn in Lab 3?', placeholder: 'Type your answer...' },
    dialogue: [
      { type: 'timing', time: '0:00 — 0:05', phase: 'Session orientation' },
      { type: 'say', text: 'Each lesson follows the same rhythm: Read, Build, Present. In Read you consume the content. In Build you apply it with the AI assistant. In Present you explain it — because if you can explain it, you own it.' },
      { type: 'note', text: 'Point to each lesson card on the slide as you name them.' },
      { type: 'say', text: 'And the Capstone — where you design an actual module for your SBU. The modules you design are real. PGB is building them this year.' },
      { type: 'say', text: "Quick warm-up before we start: what are you most curious to learn today? Type your answer in the app — I'll read a few out." },
    ],
  },
  {
    id: 3,
    title: 'Lesson 3.1: Why Build',
    layerTag: 'L2',
    color: '#1E40AF',
    heading: 'LESSON 3.1 · WHY PGB BUILDS ITS OWN AI',
    sub: '15 min',
    body: [
      { type: 'pillars', items: [
        { icon: '🔒', title: 'Own the IP', desc: 'Every model and algorithm is permanent PGB IP. No vendor owns our competitive intelligence.' },
        { icon: '☁️', title: 'Control the Stack', desc: 'No vendor lock-in. PGB defines the data model and feature roadmap on our own schedule.' },
        { icon: '📈', title: 'Build Capability', desc: "Every module grows PGB's internal AI expertise — a permanent organisational asset." },
      ]},
      { type: 'costbar', text: 'BUILD COST: PHP 923,000 one-time + PHP 68,000/yr infrastructure · 100% PGB Owned' },
    ],
    question: { id: 'q3', prompt: 'What is the most important benefit of PGB building its own AI for your SBU?', placeholder: 'Type your reflection...' },
    dialogue: [
      { type: 'timing', time: '0:05 — 0:20', phase: 'READ → BUILD → PRESENT' },
      { type: 'phase', text: 'PHASE 1 · READ' },
      { type: 'say', text: 'Pillar 1: Own the IP. Every model, pipeline, and algorithm belongs to PGB permanently. Not a vendor. Not a subscription. Ours.' },
      { type: 'say', text: 'Pillar 2: Control the Stack. We define what gets built and when. We are not waiting for a vendor release schedule.' },
      { type: 'say', text: "Pillar 3: Build Capability. Every module grows PGB's internal knowledge. You become the AI experts — not external vendors." },
      { type: 'say', text: 'Build cost: PHP 923,000 one-time plus PHP 68,000/yr. After 12 months it pays for itself.' },
      { type: 'phase', text: 'PHASE 2 · BUILD' },
      { type: 'say', text: 'A skeptical GM asks: "Why spend PHP 923,000 when we can subscribe?" Use the AI assistant to prepare your answer. 3 minutes.' },
      { type: 'phase', text: 'PHASE 3 · PRESENT' },
      { type: 'say', text: 'Now type your answer in the app: what is the most important benefit for your SBU? I want to read a few live.' },
    ],
  },
  {
    id: 4,
    title: 'Lesson 3.2: PGB SCE',
    layerTag: 'L2',
    color: '#1E40AF',
    heading: 'LESSON 3.2 · PGB SUPPLY CHAIN ENGINE',
    sub: 'Layer 2 · In-House Build · 20 min',
    body: [
      { type: 'modcards', items: [
        { q: 'Q1', title: 'Demand Forecasting', sbu: 'All SBUs', body: '4-week rolling forecast. Target: 85%→92%.' },
        { q: 'Q2', title: 'Warehouse Optimizer', sbu: 'AAC·PSC·AMICI', body: 'Real-time utilisation alerts.' },
        { q: 'Q2', title: 'Vessel Route Planner', sbu: 'AMICI only', body: 'Route optimisation + delay contingency.' },
        { q: 'Q3', title: 'Freight Reconciliation', sbu: 'All SBUs', body: 'Auto-match invoices to NetSuite POs.' },
        { q: 'Q3', title: 'SCE Recommendation Engine ★', sbu: 'All SBUs', body: 'ML-ranked actions. BI approval gate required.', highlight: true },
      ]},
      { type: 'note2', text: 'Key Principle: AI suggests. People decide. No recommendation executes without Business Integrator sign-off.' },
    ],
    question: { id: 'q4', prompt: 'Which PGB SCE module would have the biggest impact on your SBU, and why?', placeholder: 'Type your answer...' },
    dialogue: [
      { type: 'timing', time: '0:20 — 0:40', phase: 'READ → BUILD → PRESENT' },
      { type: 'phase', text: 'PHASE 1 · READ' },
      { type: 'say', text: 'PGB SCE sits on top of NetSuite and turns raw data into operational decisions. NetSuite is our database. PGB SCE is the brain that reads it.' },
      { type: 'say', text: 'Vessel Route Planner — who does this serve? AMICI exclusively. The Recommendation Engine never executes automatically — Business Integrator must approve every one.' },
      { type: 'phase', text: 'PHASE 2 · BUILD' },
      { type: 'say', text: 'MV Ligaya delayed 2 days. 3 options: wait, land reroute, split cargo. Use AI to analyze. 5 minutes.' },
      { type: 'phase', text: 'PHASE 3 · PRESENT' },
      { type: 'say', text: 'Type your answer: which module would have the biggest impact on your SBU?' },
    ],
  },
  {
    id: 5,
    title: 'Lesson 3.3: PGB AI Intel',
    layerTag: 'L3',
    color: '#0D9488',
    heading: 'LESSON 3.3 · PGB AI INTEL',
    sub: 'Layer 3 · In-House Build · 20 min',
    body: [
      { type: 'modcards', items: [
        { q: 'Q1', title: 'Predictive Maintenance', sbu: 'AMICI·AAC·PSC', body: 'Anomaly detection. MV Paz first.' },
        { q: 'Q2', title: 'Skills Analytics Engine', sbu: 'SEAMAN·SKILLS·PSI·PSEFI', body: 'Competency scoring per entity.' },
        { q: 'Q3', title: 'STEP UP Recommender', sbu: 'All HCD', body: 'Auto-generate training priorities.' },
        { q: 'Q4', title: 'Cross-Layer Risk Aggregator ⚠️', sbu: 'All SBUs · COO', body: 'Compound risk ≥60% → COO escalation.', highlight: true, riskColor: true },
        { q: 'Q4', title: 'Executive KPI Dashboard', sbu: 'All SBUs · Leaders', body: 'L1–L3 single pane.' },
      ]},
      { type: 'note2', text: 'Compound Risk Example (68%): MV Paz engine anomaly (High) + W29 demand surge +18% + AAC Batching Plant B2 at 73% breakdown probability → COO escalation triggered.', danger: true },
    ],
    question: { id: 'q5', prompt: 'How could PGB AI Intel have changed a decision your team made in the past 3 months?', placeholder: 'Be specific...' },
    dialogue: [
      { type: 'timing', time: '0:40 — 1:00', phase: 'READ → BUILD → PRESENT' },
      { type: 'phase', text: 'PHASE 1 · READ' },
      { type: 'say', text: "Layer 2 runs today's supply chain. Layer 3 prepares us for tomorrow. Layer 2 asks what to do now. Layer 3 asks what's about to go wrong." },
      { type: 'say', text: 'MV Paz flagged HIGH risk — action by July 4. Without PGB AI Intel we would not see that until the engine fails. At sea. Mid-voyage.' },
      { type: 'say', text: 'Cross-Layer Risk Aggregator — the most powerful module. MV Paz + W29 demand surge + Batching Plant B2 at 73%. Compound confidence 68% → COO escalation triggered automatically.' },
      { type: 'phase', text: 'PHASE 2 · BUILD' },
      { type: 'say', text: 'Draft the COO escalation memo for this compound risk. 5 minutes.' },
      { type: 'phase', text: 'PHASE 3 · PRESENT' },
      { type: 'say', text: 'Type your answer: how could PGB AI Intel have changed a recent decision on your team?' },
    ],
  },
  {
    id: 6,
    title: 'Lesson 3.4: Architecture',
    layerTag: 'L3',
    color: '#7C3AED',
    heading: 'LESSON 3.4 · THE 3-LAYER ARCHITECTURE',
    sub: 'How It All Connects · 15 min',
    body: [
      { type: 'handoffs', items: [
        { n: '1', from: 'NetSuite → PGB SCE', owner: 'BI + IT · Manual gate', detail: 'BI sign-off required before every sync', color: '#C0392B' },
        { n: '2', from: 'PGB SCE → PGB AI Intel', owner: 'IT · Automated', detail: 'Continuous API feed; IT monitors drift', color: '#1E40AF' },
        { n: '3', from: 'PGB AI Intel → Action', owner: 'BI · Manual routing', detail: 'BI classifies & routes every alert', color: '#0D9488' },
      ]},
    ],
    question: { id: 'q6', prompt: 'Which handoff point is most critical for platform success, and what would you do to protect it?', placeholder: 'Type your answer...' },
    dialogue: [
      { type: 'timing', time: '1:00 — 1:15', phase: 'READ → BUILD → PRESENT' },
      { type: 'phase', text: 'PHASE 1 · READ' },
      { type: 'say', text: 'Handoff 1: NetSuite to SCE. Owner: BI + IT. Failed records go back to the SBU encoder — never forward.' },
      { type: 'say', text: 'Handoff 2: SCE to AI Intel. Owner: IT. Automated, continuous, no manual gate.' },
      { type: 'say', text: 'Handoff 3: AI Intel to Action. Owner: BI. Every alert routed: equipment → Maintenance Head, skills → HCD, compound risk → COO.' },
      { type: 'phase', text: 'PHASE 2 · BUILD' },
      { type: 'say', text: 'Ask AI to explain the architecture using an analogy for a new department head. 5 minutes.' },
      { type: 'phase', text: 'PHASE 3 · PRESENT' },
      { type: 'say', text: 'Type your answer: which handoff is most critical, and how would you protect it?' },
    ],
  },
  {
    id: 7,
    title: 'Capstone',
    layerTag: '★',
    color: '#F59E0B',
    heading: '★ CAPSTONE · DESIGN YOUR PGB AI PLATFORM MODULE',
    sub: '20 min',
    body: [
      { type: 'capsteps', items: [
        { n: '1', label: 'SELECT', body: 'Choose your module from 6 options' },
        { n: '2', label: 'BUILD', body: 'Complete the 5-field Module Design Brief with AI assistance' },
        { n: '3', label: 'PRESENT', body: '90-second presentation: module, SBU, data, output path, KPI' },
      ]},
    ],
    question: { id: 'q7', prompt: 'Name your module and the one KPI that proves it works.', placeholder: 'e.g. STEP UP Recommender — 85% skills score by Q3 2026' },
    dialogue: [
      { type: 'timing', time: '1:15 — 1:35', phase: 'BUILD → PRESENT' },
      { type: 'say', text: "We've arrived at the Capstone. The modules you design are real — PGB is building them in 2026." },
      { type: 'note', text: "Push on the KPI field — not 'improved accuracy' but '85% forecast accuracy by Q3 2026.'" },
      { type: 'say', text: 'Select your module. Open the AI Design Assistant. Complete all 5 fields. 10 minutes.' },
      { type: 'say', text: 'Now submit your module name and KPI in the app — I will call on a few of you to present live.' },
    ],
  },
  {
    id: 8,
    title: 'Closing',
    layerTag: null,
    color: '#0D1B3D',
    heading: 'CLOSING · SYNTHESIS & COMMITMENT',
    sub: '5 min',
    body: [
      { type: 'questions3', items: [
        '01 · What is one thing from Lab 3 that changed how you think about AI in your SBU?',
        '02 · What is one thing you can do in 30 days to prepare your team or data?',
        '03 · Who else in PGB needs to understand this platform — will you tell them?',
      ]},
    ],
    question: { id: 'q8', prompt: 'Your one commitment for the next 30 days:', placeholder: 'Type your commitment...' },
    dialogue: [
      { type: 'timing', time: '1:35 — 1:40', phase: 'SYNTHESIS · COMMITMENT · CLOSE' },
      { type: 'say', text: 'In Labs 1 and 2 we studied platforms you buy. In Lab 3 we designed one you build. The modules you designed — PGB is building them.' },
      { type: 'say', text: 'Three closing questions. Type your commitment for the next 30 days — I will read a few out before we close.' },
      { type: 'say', text: 'Pagsalig — trust. Hiniusang Pagkugi — unified effort. Pagpalambo — permanent growth. Lab 3 is complete. The build begins.' },
    ],
  },
]
